version: '3'
services: 
  web:
    container_name: "${PROJECT_NAME}_web"
    build:
      context: ./
      dockerfile: Web.DockerFile
    ports: 
      - "80:80"
      - "443:443"
      - "9000:9000"
    volumes:
      - ./codebase:/var/www/html
  db: 
    container_name: "${PROJECT_NAME}_db"
    image: mariadb
    ports: 
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DB
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PW
    volumes: 
      - ./codebase:/var/www/html
  node: 
    container_name: "${PROJECT_NAME}_node"
    build:
      context: ./
      dockerfile: Node.DockerFile
    volumes:
      - ./codebase:/var/www/html
    command: "tail -f /dev/null"
    working_dir: /var/www/html
